#!/usr/bin/env zsh 

export DOTFILES=$HOME/.dotfiles
STOW_FOLDERS="nvim"

# Creating directory for nvim config
echo "Executing initialization script for dotfiles"

# Stowing everything
# This will specify everything in $STOW_FOLDERS
# as a directory inside .dotfiles and stow it
# stow will make a symbolic link with everything in here
# and point to the directory below the directory we are running it in
# for example /home/jarrod/.dotfiles running this script in there
# will link everything to /home/jarrod
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g") 
do
    echo "$folder"
    stow -D $folder
    stow $folder
done
